import Foundation

nonisolated extension SharedSprites {

    // MARK: - Training

    // Boxing heavy bag — shifted left for trailing padding
    //
    //    ....##..........  chain
    //    ....##..........  chain
    //    ...####.........  bracket
    //    .########.......  body (flat top)
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......  body (flat bottom)
    //    ..######........  rounded
    //    ...####.........  rounded

    static let trainingTarget = SpriteFrame(rows: [
        0x0C00, //  ....##..........  chain
        0x0C00, //  ....##..........  chain
        0x0C00, //  ....##..........  chain
        0x1E00, //  ...####.........  bracket
        0x7F80, //  .########.......  body
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x3F00, //  ..######........  rounded bottom
        0x1E00  //  ...####.........
    ])

    // Heavy bag punched right — body shifted, impact lines
    static let trainingTargetHit = SpriteFrame(rows: [
        0x0C00, //  ....##..........  chain (anchored)
        0x0C00, //  ....##..........  chain
        0x0600, //  .....##.........  chain bends right
        0x0F00, //  ....####........  bracket shifted
        0x3FC0, //  ..########......  body shifted right
        0x3FC0, //  ..########......
        0xBFC0, //  #.########......  impact line
        0x7FC0, //  .#########......  impact line
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x1F80, //  ...######.......  rounded bottom
        0x0F00  //  ....####........
    ])

    // Heavy bag recoiling left — body shifted left
    static let trainingTargetRecoil = SpriteFrame(rows: [
        0x0C00, //  ....##..........  chain (anchored)
        0x0C00, //  ....##..........  chain
        0x1800, //  ...##...........  chain bends left
        0x3C00, //  ..####..........  bracket shifted
        0xFF00, //  ########........  body shifted left
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0x7E00, //  .######.........  rounded bottom
        0x3C00  //  ..####..........
    ])

    // Miss whiff — arc-shaped motion lines showing an empty swing
    static let trainingMiss = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x4000, //  .#..............
        0x2000, //  ..#.............
        0x3000, //  ..##............
        0x1800, //  ...##...........
        0x0C00, //  ....##..........
        0x0C00, //  ....##..........
        0x1800, //  ...##...........
        0x3000, //  ..##............
        0x2000, //  ..#.............
        0x4000, //  .#..............
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Victory sparkle frame 1 — stars scattered
    static let trainingStar1 = SpriteFrame(rows: [
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x8001, //  #..............#
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Victory sparkle frame 2 — stars shifted
    static let trainingStar2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x2004, //  ..#..........#..
        0x0000, //  ................
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x0000, //  ................
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x2004, //  ..#..........#..
        0x0000, //  ................
        0x0000  //  ................
    ])

    // MARK: - Projectile

    // Energy ball at far left, high position (rows 2-5)
    static let projectileHighBase = SpriteFrame(rows: [
        0x0000, 0x0000,
        0x6000, //  .##.............
        0xF000, //  ####............
        0xF000, //  ####............
        0x6000, //  .##.............
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // Energy ball at far left, medium position (rows 6-9)
    static let projectileMidBase = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x6000, //  .##.............
        0xF000, //  ####............
        0xF000, //  ####............
        0x6000, //  .##.............
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // Energy ball at far left, low position (rows 10-13)
    static let projectileLowBase = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x6000, //  .##.............
        0xF000, //  ####............
        0xF000, //  ####............
        0x6000, //  .##.............
        0x0000, 0x0000
    ])

    // AUDIT 2026-06-24: projectileHigh/Mid/Low + trainingMissSequence are drawn but
    // never played (training shows hit/miss streaks instead). Future use or remove.
    /// High projectile traveling left-to-right (non-looping)
    static let projectileHigh = SpriteAnimation(
        frames: [
            projectileHighBase,
            projectileHighBase.shiftedRight(4),
            projectileHighBase.shiftedRight(8),
            projectileHighBase.shiftedRight(12)
        ],
        frameDuration: 0.15,
        loops: false
    )

    /// Medium projectile traveling left-to-right (non-looping)
    static let projectileMid = SpriteAnimation(
        frames: [
            projectileMidBase,
            projectileMidBase.shiftedRight(4),
            projectileMidBase.shiftedRight(8),
            projectileMidBase.shiftedRight(12)
        ],
        frameDuration: 0.15,
        loops: false
    )

    /// Low projectile traveling left-to-right (non-looping)
    static let projectileLow = SpriteAnimation(
        frames: [
            projectileLowBase,
            projectileLowBase.shiftedRight(4),
            projectileLowBase.shiftedRight(8),
            projectileLowBase.shiftedRight(12)
        ],
        frameDuration: 0.15,
        loops: false
    )

    // Punching bag hit sequence: hit → recoil → settle
    static let trainingHitSequence = SpriteAnimation(
        frames: [trainingTargetHit, trainingTargetRecoil, trainingTarget],
        frameDuration: 0.2,
        loops: false
    )

    // Miss whiff animation: lines appear then fade
    static let trainingMissSequence = SpriteAnimation(
        frames: [trainingMiss, .empty],
        frameDuration: 0.35,
        loops: false
    )

    // Victory sparkle looping
    static let trainingVictorySparkle = SpriteAnimation(
        frames: [trainingStar1, trainingStar2],
        frameDuration: 0.3,
        loops: true
    )
}
