import Foundation

/// Egg animations and status icons shared across the app.
/// Bitmaps are 16x16 monochrome, one `UInt16` per row with the MSB as the
/// leftmost pixel.
nonisolated enum SharedSprites {

    // MARK: - Egg

    /// The egg's idle animation, looping between the still and wobble frames.
    static let egg = SpriteAnimation(
        frames: [eggStill, eggWobble],
        frameDuration: 0.8,
        loops: true
    )

    /// The hatching animation, played once as the egg cracks open.
    static let eggCrack = SpriteAnimation(
        frames: [eggCrack1, eggCrack2, eggCrack3],
        frameDuration: 0.6,
        loops: false
    )

    private static let eggStill = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x03C0, //  ......####......
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x03C0, //  ......####......
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    private static let eggWobble = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x01E0, //  .......####.....  shifted right
        0x07F8, //  .....########...
        0x0FFC, //  ....##########..
        0x1FFE, //  ...############.
        0x1FFE, //  ...############.
        0x1FFE, //  ...############.
        0x1FFE, //  ...############.
        0x0FFC, //  ....##########..
        0x07F8, //  .....########...
        0x01E0, //  .......####.....
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    private static let eggCrack1 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x03C0, //  ......####......
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x3FFC, //  ..############..
        0x2814, //  ..#.#......#.#..  crack line
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x03C0, //  ......####......
        0x0000, 0x0000, 0x0000
    ])

    private static let eggCrack2 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x03C0,
        0x0FF0,
        0x1818, //  ...##......##...  crack widens
        0x3FFC,
        0x2004, //  ..#..........#..  big gap
        0x3FFC,
        0x1818, //  ...##......##...
        0x1FF8,
        0x0FF0,
        0x03C0,
        0x0000, 0x0000, 0x0000
    ])

    private static let eggCrack3 = SpriteFrame(rows: [
        0x1008, //  ...#.........#..  fragment
        0x0810, //  ....#......#....  fragment
        0x0000,
        0x0240, //  ......#..#......  shell piece
        0x0C30, //  ....##....##....  left/right halves
        0x1818, //  ...##......##...
        0x1818, //  ...##......##...
        0x0000, //  ................  gap (baby emerging)
        0x0000, //  ................
        0x1818, //  ...##......##...
        0x1818, //  ...##......##...
        0x0C30, //  ....##....##....
        0x0240, //  ......#..#......
        0x0000,
        0x0810, //  ....#......#....
        0x1008  //  ...#.........#..
    ])

    // MARK: - Status Icons

    /// Skull and crossbones shown as the top-right status icon.
    static let skull = SpriteFrame(rows: [
        0x0000, //  ................
        0x0780, //  .....####.......  skull cap
        0x0FC0, //  ....######......  skull wide
        0x0B40, //  ....#.##.#......  eye sockets
        0x0FC0, //  ....######......  lower skull
        0x0780, //  .....####.......  jaw
        0x0480, //  .....#..#.......  teeth
        0x0000, //  ................
        0x0480, //  .....#..#.......  bone tips
        0x0300, //  ......##........  bone cross
        0x0480, //  .....#..#.......  bone tips
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    /// Tombstone shown as a status icon.
    static let grave = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x07E0, //  .....######.....  rounded top
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x1BD8, //  ...##.####.##...  cross horizontal
        0x1E78, //  ...####..####...  cross center
        0x1BD8, //  ...##.####.##...  cross horizontal
        0x1FF8, //  ...##########...
        0x1FF8, //  ...##########...
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x0FF0, //  ....########....
        0x3FFC, //  ..############..  ground
        0x0000, //  ................
        0x0000  //  ................
    ])
}
