import Foundation

/// Common sprites shared across the app: egg, food, status icons, and effects.
/// All bitmaps are 16x16 monochrome encoded as UInt16 rows (MSB = left).
nonisolated enum SharedSprites {

    // MARK: - Egg

    /// Egg sitting still, then wobbling side-to-side.
    static let egg = SpriteAnimation(
        frames: [eggStill, eggWobble],
        frameDuration: 0.8,
        loops: true
    )

    /// Egg cracking sequence: small crack, big crack, hatching burst.
    static let eggCrack = SpriteAnimation(
        frames: [eggCrack1, eggCrack2, eggCrack3],
        frameDuration: 0.6,
        loops: false
    )

    // Egg still - oval shape centered
    //
    //    ......####......
    //    ....########....
    //    ...##########...
    //    ..############..
    //    ..############..
    //    ..############..
    //    ..############..
    //    ...##########...
    //    ....########....
    //    ......####......

    private static let eggStill = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x03C0, //  ......####......
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x03C0, //  ......####......
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Egg wobbled to the right
    private static let eggWobble = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x01E0, //  .......####.....  shifted right
        0x07F8, //  .....########...
        0x0FFC, //  ....##########..
        0x1FFE, //  ...############.
        0x1FFE, //  ...############.
        0x1FFE, //  ...############.
        0x1FFE, //  ...############.
        0x0FFC, //  ....##########..
        0x07F8, //  .....########...
        0x01E0, //  .......####.....
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Egg with small crack line across middle
    private static let eggCrack1 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x03C0, //  ......####......
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x3FFC, //  ..############..
        0x2814, //  ..#.#......#.#..  crack line
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x03C0, //  ......####......
        0x0000, 0x0000, 0x0000
    ])

    // Egg with large crack, splitting open
    private static let eggCrack2 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x03C0,
        0x0FF0,
        0x1818, //  ...##......##...  crack widens
        0x3FFC,
        0x2004, //  ..#..........#..  big gap
        0x3FFC,
        0x1818, //  ...##......##...
        0x1FF8,
        0x0FF0,
        0x03C0,
        0x0000, 0x0000, 0x0000
    ])

    // Egg bursting open - shell fragments flying
    private static let eggCrack3 = SpriteFrame(rows: [
        0x1008, //  ...#.........#..  fragment
        0x0810, //  ....#......#....  fragment
        0x0000,
        0x0240, //  ......#..#......  shell piece
        0x0C30, //  ....##....##....  left/right halves
        0x1818, //  ...##......##...
        0x1818, //  ...##......##...
        0x0000, //  ................  gap (baby emerging)
        0x0000, //  ................
        0x1818, //  ...##......##...
        0x1818, //  ...##......##...
        0x0C30, //  ....##....##....
        0x0240, //  ......#..#......
        0x0000,
        0x0810, //  ....#......#....
        0x1008  //  ...#.........#..
    ])

    // MARK: - Poop

    // Small pile shape
    //    .......##.......
    //    ......####......
    //    .....##..##.....
    //    ....########....
    //    ...##########...
    //    ....########....

    static let poop = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0100, //  .......#........  steam
        0x0080, //  ........#.......  steam
        0x0180, //  .......##.......  top
        0x03C0, //  ......####......
        0x0660, //  .....##..##.....  face indent
        0x0FF0, //  ....########....  middle
        0x1FF8, //  ...##########...  base
        0x0FF0, //  ....########....
        0x0000, //  ................
        0x0000  //  ................
    ])

    // MARK: - Food

    // Meat: compact drumstick shifted left for trailing padding
    //    ..######........  dome
    //    .########.......  widest
    //    .########.......
    //    ..######........
    //    ....##..........  bone shaft
    //    ....##..........
    //    ...####.........  bone knob
    //    ....##..........

    static let meat = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x3F00, //  ..######........  dome top
        0x7F80, //  .########.......  widest
        0x7F80, //  .########.......
        0x3F00, //  ..######........  dome bottom
        0x0C00, //  ....##..........  shaft
        0x0C00, //  ....##..........
        0x1E00, //  ...####.........  knob
        0x0C00, //  ....##..........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Vitamin: compact capsule shifted left for trailing padding
    //    ...####.........  rounded top
    //    ..######........  body
    //    ..######........
    //    ..##..##........  center divide
    //    ..######........
    //    ..######........
    //    ...####.........  rounded bottom

    static let vitamin = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  rounded top
        0x3F00, //  ..######........  body
        0x3F00, //  ..######........
        0x3300, //  ..##..##........  center divide
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x1E00, //  ...####.........  rounded bottom
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // MARK: - Status Icons

    // Skull and crossbones
    //    .....######.....
    //    ....########....
    //    ...##.####.##...
    //    ...##########...
    //    ....########....
    //    .....######.....
    //    ......####......
    //    ...############.
    //    ....##.##.##....
    //    ...############.

    static let skull = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x07E0, //  .....######.....
        0x0FF0, //  ....########....
        0x1BD8, //  ...##.####.##...  eye sockets
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x07E0, //  .....######.....  nose
        0x0550, //  .....#.#.#.#....  teeth
        0x03C0, //  ......####......  neck
        0x1FF8, //  ...##########...  crossbones
        0x0DB0, //  ....##.##.##....
        0x1FF8, //  ...##########...
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Tombstone / grave marker
    //    .....######.....
    //    ....########....
    //    ...##########...
    //    ...##.####.##...   R.I.P. cross
    //    ...####..####...
    //    ...##.####.##...
    //    ...##########...
    //    ...##########...
    //    ...##########...
    //    ....########....
    //    ..##############

    static let grave = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x07E0, //  .....######.....  rounded top
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x1BD8, //  ...##.####.##...  cross horizontal
        0x1E78, //  ...####..####...  cross center
        0x1BD8, //  ...##.####.##...  cross horizontal
        0x1FF8, //  ...##########...
        0x1FF8, //  ...##########...
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x0FF0, //  ....########....
        0x3FFC, //  ..############..  ground
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Small heart shape
    //    ..##...##.......
    //    .####.####......
    //    .#########......
    //    ..########......
    //    ...######.......
    //    ....####........
    //    .....##.........

    static let heart = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x3600, //  ..##.##.........
        0x7F00, //  .#######........
        0x7F00, //  .#######........
        0x7F00, //  .#######........
        0x3E00, //  ..#####.........
        0x1C00, //  ...###..........
        0x0800, //  ....#...........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // MARK: - ZZZ Sleep

    // Z letters floating upward, two frames
    static let zzz = SpriteAnimation(
        frames: [zzzFrame1, zzzFrame2],
        frameDuration: 0.8,
        loops: true
    )

    // Frame 1: two Z's at different heights
    private static let zzzFrame1 = SpriteFrame(rows: [
        0x001E, //  ...........####.  top Z
        0x0004, //  .............#..
        0x0008, //  ............#...
        0x001E, //  ...........####.
        0x0000, //  ................
        0x0000, //  ................
        0x00F0, //  ........####....  lower Z
        0x0020, //  ..........#.....
        0x0040, //  .........#......
        0x00F0, //  ........####....
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Frame 2: Z's shifted up
    private static let zzzFrame2 = SpriteFrame(rows: [
        0x000F, //  ............####  top Z shifted
        0x0002, //  ..............#.
        0x0004, //  .............#..
        0x000F, //  ............####
        0x0000,
        0x001E, //  ...........####.  middle Z
        0x0004, //  .............#..
        0x0008, //  ............#...
        0x001E, //  ...........####.
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // MARK: - Animation Effects

    /// Landing dust puffs at bottom of frame
    static let landingDust = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000,
        0x0810, //  ....#......#....
        0x1428, //  ...#.#....#.#...
        0x0810  //  ....#......#....
    ])

    /// Impact starburst on the right side of frame
    static let impactBurst = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x0010, //  ...........#....
        0x0008, //  ............#...
        0x0004, //  .............#..
        0x007E, //  .........######.
        0x00FF, //  ........########
        0x007E, //  .........######.
        0x0004, //  .............#..
        0x0008, //  ............#...
        0x0010, //  ...........#....
        0x0000, 0x0000, 0x0000, 0x0000
    ])

    /// Z overlay — position 1 (lower right)
    static let sleepZ1 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x003C, //  ..........####..
        0x0008, //  ............#...
        0x0010, //  ...........#....
        0x003C, //  ..........####..
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    /// Z overlay — position 2 (mid right)
    static let sleepZ2 = SpriteFrame(rows: [
        0x0000,
        0x001E, //  ...........####.
        0x0004, //  .............#..
        0x0008, //  ............#...
        0x001E, //  ...........####.
        0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000
    ])

    /// Z overlay — position 3 (two Z's, high + low)
    static let sleepZ3 = SpriteFrame(rows: [
        0x001E, //  ...........####.
        0x0004, //  .............#..
        0x0008, //  ............#...
        0x001E, //  ...........####.
        0x0000, 0x0000,
        0x003C, //  ..........####..
        0x0008, //  ............#...
        0x0010, //  ...........#....
        0x003C, //  ..........####..
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // MARK: - Training

    // Boxing heavy bag — shifted left for trailing padding
    //
    //    ....##..........  chain
    //    ....##..........  chain
    //    ...####.........  bracket
    //    .########.......  body (flat top)
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......
    //    .########.......  body (flat bottom)
    //    ..######........  rounded
    //    ...####.........  rounded

    static let trainingTarget = SpriteFrame(rows: [
        0x0C00, //  ....##..........  chain
        0x0C00, //  ....##..........  chain
        0x0C00, //  ....##..........  chain
        0x1E00, //  ...####.........  bracket
        0x7F80, //  .########.......  body
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x7F80, //  .########.......
        0x3F00, //  ..######........  rounded bottom
        0x1E00  //  ...####.........
    ])

    // Heavy bag punched right — body shifted, impact lines
    static let trainingTargetHit = SpriteFrame(rows: [
        0x0C00, //  ....##..........  chain (anchored)
        0x0C00, //  ....##..........  chain
        0x0600, //  .....##.........  chain bends right
        0x0F00, //  ....####........  bracket shifted
        0x3FC0, //  ..########......  body shifted right
        0x3FC0, //  ..########......
        0xBFC0, //  #.########......  impact line
        0x7FC0, //  .#########......  impact line
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x1F80, //  ...######.......  rounded bottom
        0x0F00  //  ....####........
    ])

    // Heavy bag recoiling left — body shifted left
    static let trainingTargetRecoil = SpriteFrame(rows: [
        0x0C00, //  ....##..........  chain (anchored)
        0x0C00, //  ....##..........  chain
        0x1800, //  ...##...........  chain bends left
        0x3C00, //  ..####..........  bracket shifted
        0xFF00, //  ########........  body shifted left
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0xFF00, //  ########........
        0x7E00, //  .######.........  rounded bottom
        0x3C00  //  ..####..........
    ])

    // Miss whiff — arc-shaped motion lines showing an empty swing
    static let trainingMiss = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x4000, //  .#..............
        0x2000, //  ..#.............
        0x3000, //  ..##............
        0x1800, //  ...##...........
        0x0C00, //  ....##..........
        0x0C00, //  ....##..........
        0x1800, //  ...##...........
        0x3000, //  ..##............
        0x2000, //  ..#.............
        0x4000, //  .#..............
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Victory sparkle frame 1 — stars scattered
    static let trainingStar1 = SpriteFrame(rows: [
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x8001, //  #..............#
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Victory sparkle frame 2 — stars shifted
    static let trainingStar2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x2004, //  ..#..........#..
        0x0000, //  ................
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x0000, //  ................
        0x0100, //  .......#........
        0x0280, //  ......#.#.......
        0x0100, //  .......#........
        0x0000, //  ................
        0x2004, //  ..#..........#..
        0x0000, //  ................
        0x0000  //  ................
    ])

    // MARK: - Projectile

    // Energy ball at far left, high position (rows 2-5)
    static let projectileHighBase = SpriteFrame(rows: [
        0x0000, 0x0000,
        0x6000, //  .##.............
        0xF000, //  ####............
        0xF000, //  ####............
        0x6000, //  .##.............
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // Energy ball at far left, medium position (rows 6-9)
    static let projectileMidBase = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x6000, //  .##.............
        0xF000, //  ####............
        0xF000, //  ####............
        0x6000, //  .##.............
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // Energy ball at far left, low position (rows 10-13)
    static let projectileLowBase = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x6000, //  .##.............
        0xF000, //  ####............
        0xF000, //  ####............
        0x6000, //  .##.............
        0x0000, 0x0000
    ])

    /// High projectile traveling left-to-right (non-looping)
    static let projectileHigh = SpriteAnimation(
        frames: [
            projectileHighBase,
            projectileHighBase.shiftedRight(4),
            projectileHighBase.shiftedRight(8),
            projectileHighBase.shiftedRight(12)
        ],
        frameDuration: 0.15,
        loops: false
    )

    /// Medium projectile traveling left-to-right (non-looping)
    static let projectileMid = SpriteAnimation(
        frames: [
            projectileMidBase,
            projectileMidBase.shiftedRight(4),
            projectileMidBase.shiftedRight(8),
            projectileMidBase.shiftedRight(12)
        ],
        frameDuration: 0.15,
        loops: false
    )

    /// Low projectile traveling left-to-right (non-looping)
    static let projectileLow = SpriteAnimation(
        frames: [
            projectileLowBase,
            projectileLowBase.shiftedRight(4),
            projectileLowBase.shiftedRight(8),
            projectileLowBase.shiftedRight(12)
        ],
        frameDuration: 0.15,
        loops: false
    )

    // Punching bag hit sequence: hit → recoil → settle
    static let trainingHitSequence = SpriteAnimation(
        frames: [trainingTargetHit, trainingTargetRecoil, trainingTarget],
        frameDuration: 0.2,
        loops: false
    )

    // Miss whiff animation: lines appear then fade
    static let trainingMissSequence = SpriteAnimation(
        frames: [trainingMiss, .empty],
        frameDuration: 0.35,
        loops: false
    )

    // Victory sparkle looping
    static let trainingVictorySparkle = SpriteAnimation(
        frames: [trainingStar1, trainingStar2],
        frameDuration: 0.3,
        loops: true
    )

    // MARK: - Feeding Sprites

    // Meat steaming — frame 1: steam wisps above compact drumstick
    static let meatSteaming1 = SpriteFrame(rows: [
        0x0A00, //  ....#.#.........  steam wisps
        0x0600, //  .....##.........  steam
        0x0000, //  ................
        0x3F00, //  ..######........  dome top
        0x7F80, //  .########.......  widest
        0x7F80, //  .########.......
        0x3F00, //  ..######........  dome bottom
        0x0C00, //  ....##..........  shaft
        0x0C00, //  ....##..........
        0x1E00, //  ...####.........  knob
        0x0C00, //  ....##..........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Meat steaming — frame 2: steam wisps shifted
    static let meatSteaming2 = SpriteFrame(rows: [
        0x1400, //  ...#.#..........  steam shifted
        0x0A00, //  ....#.#.........  steam
        0x0000, //  ................
        0x3F00, //  ..######........  dome top
        0x7F80, //  .########.......  widest
        0x7F80, //  .########.......
        0x3F00, //  ..######........  dome bottom
        0x0C00, //  ....##..........  shaft
        0x0C00, //  ....##..........
        0x1E00, //  ...####.........  knob
        0x0C00, //  ....##..........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Meat after first bite — dome reduced
    static let meatBite1 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x3F00, //  ..######........  reduced dome
        0x7F80, //  .########.......
        0x3F00, //  ..######........
        0x0C00, //  ....##..........  shaft
        0x0C00, //  ....##..........
        0x1E00, //  ...####.........  knob
        0x0C00, //  ....##..........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Meat after second bite — small scrap, bone visible
    static let meatBite2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  small scrap
        0x0C00, //  ....##..........  bone visible
        0x0C00, //  ....##..........
        0x0C00, //  ....##..........
        0x1E00, //  ...####.........  knob
        0x0C00, //  ....##..........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Bare bone — compact knob-shaft-knob
    static let meatBone = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  top knob
        0x3300, //  ..##..##........  knob sides
        0x1E00, //  ...####.........
        0x0C00, //  ....##..........  shaft
        0x0C00, //  ....##..........
        0x0C00, //  ....##..........
        0x1E00, //  ...####.........  bottom knob
        0x3300, //  ..##..##........
        0x1E00, //  ...####.........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Vitamin gleaming — frame 1: sparkle upper-right
    static let vitaminGleaming1 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0080, //  ........#.......  sparkle top
        0x0140, //  .......#.#......  sparkle arms
        0x0080, //  ........#.......  sparkle bottom
        0x1E00, //  ...####.........  capsule top
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x3300, //  ..##..##........  divide
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x1E00, //  ...####.........  capsule bottom
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Vitamin gleaming — frame 2: sparkle lower-left
    static let vitaminGleaming2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  capsule top
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x3300, //  ..##..##........  divide
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x1E00, //  ...####.........  capsule bottom
        0x4000, //  .#..............  sparkle top
        0xA000, //  #.#.............  sparkle arms
        0x4000, //  .#..............  sparkle bottom
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Vitamin after first bite — bottom shrunk
    static let vitaminBite1 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  capsule top
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x3300, //  ..##..##........  divide
        0x3F00, //  ..######........
        0x1E00, //  ...####.........  rounded
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Vitamin after second bite — top half only
    static let vitaminBite2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  capsule top
        0x3F00, //  ..######........
        0x3F00, //  ..######........
        0x1E00, //  ...####.........  rounded bottom
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Vitamin empty — compact hollow outline
    static let vitaminEmpty = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x1E00, //  ...####.........  outline top
        0x2100, //  ..#....#........  outline sides
        0x2100, //  ..#....#........
        0x1E00, //  ...####.........  outline bottom
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Satisfaction heart — centered, floats where the food was
    //
    //    .....##.##......
    //    ....########....
    //    ....########....
    //    .....######.....
    //    ......####......
    //    .......##.......

    static let satisfactionHeart = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x06C0, //  .....##.##......
        0x0FF0, //  ....########....
        0x0FF0, //  ....########....
        0x07E0, //  .....######.....
        0x03C0, //  ......####......
        0x0180, //  .......##.......
        0x0000, //  ................
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // MARK: - Feeding Animations

    /// Steaming meat — steam wisps alternate (looping)
    static let meatServing = SpriteAnimation(
        frames: [meatSteaming1, meatSteaming2],
        frameDuration: 0.4,
        loops: true
    )

    /// Gleaming vitamin — sparkle alternates position (looping)
    static let vitaminServing = SpriteAnimation(
        frames: [vitaminGleaming1, vitaminGleaming2],
        frameDuration: 0.5,
        loops: true
    )

    // MARK: - Cleaning

    // Water drops falling — frame 1 (over poop area at rightSprite offset)
    static let waterDrops1 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0490, //  .....#..#..#....
        0x0000, //  ................
        0x0240, //  ......#..#......
        0x0000, //  ................
        0x0490, //  .....#..#..#....
        0x0000, //  ................
        0x0240, //  ......#..#......
        0x0000, //  ................
        0x0490, //  .....#..#..#....
        0x0000, //  ................
        0x0240, //  ......#..#......
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Water drops falling — frame 2 (shifted down)
    static let waterDrops2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0490, //  .....#..#..#....
        0x0000, //  ................
        0x0240, //  ......#..#......
        0x0000, //  ................
        0x0490, //  .....#..#..#....
        0x0000, //  ................
        0x0240, //  ......#..#......
        0x0000, //  ................
        0x0490, //  .....#..#..#....
        0x0000, //  ................
        0x0240, //  ......#..#......
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Clean sparkle — frame 1
    static let cleanSparkle1 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000,
        0x0800, //  ....#...........
        0x1400, //  ...#.#..........
        0x0800, //  ....#...........
        0x0000, 0x0000,
        0x0080, //  ........#.......
        0x0140, //  .......#.#......
        0x0080, //  ........#.......
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    ])

    // Clean sparkle — frame 2
    static let cleanSparkle2 = SpriteFrame(rows: [
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0020, //  ..........#.....
        0x0050, //  .........#.#....
        0x0020, //  ..........#.....
        0x0000, 0x0000,
        0x0200, //  ......#.........
        0x0500, //  .....#.#........
        0x0200, //  ......#.........
        0x0000, 0x0000, 0x0000, 0x0000
    ])

    /// Falling water drops for shower cleaning (looping)
    static let waterDrops = SpriteAnimation(
        frames: [waterDrops1, waterDrops2],
        frameDuration: 0.2,
        loops: true
    )

    /// Clean sparkles after washing (looping)
    static let cleanSparkle = SpriteAnimation(
        frames: [cleanSparkle1, cleanSparkle2],
        frameDuration: 0.3,
        loops: true
    )

    // MARK: - Battle

    // Battle clash — 2-frame collision burst (centered)
    static let battleClash = SpriteAnimation(
        frames: [explosion1, explosion2],
        frameDuration: 0.3,
        loops: false
    )

    // Battle miss — streaking lines whizzing past (projectile missed)
    //
    // Frame 1: diagonal streaks flying right-to-left
    //    ..............#.
    //    ............##..
    //    ................
    //    .......#........
    //    .....##.........
    //    ................
    //    ................
    //    .............#..
    //    ...........##...
    //    ................
    //    ................
    //    ....#...........
    //    ..##............
    //    ................

    private static let battleMiss1 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0002, //  ..............#.
        0x000C, //  ............##..
        0x0000, //  ................
        0x0100, //  .......#........
        0x0600, //  .....##.........
        0x0000, //  ................
        0x0000, //  ................
        0x0008, //  .............#..
        0x0030, //  ..........##....
        0x0000, //  ................
        0x0000, //  ................
        0x0800, //  ....#...........
        0x3000, //  ..##............
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Frame 2: streaks shifted left (whizzing past)
    private static let battleMiss2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0008, //  .............#..
        0x0030, //  ..........##....
        0x0000, //  ................
        0x0400, //  .....#..........
        0x1800, //  ...##...........
        0x0000, //  ................
        0x0000, //  ................
        0x0020, //  ..........#.....
        0x00C0, //  ........##......
        0x0000, //  ................
        0x0000, //  ................
        0x2000, //  ..#.............
        0xC000, //  ##..............
        0x0000, //  ................
        0x0000  //  ................
    ])

    /// Battle miss — streaks whizzing past (non-looping)
    static let battleMiss = SpriteAnimation(
        frames: [battleMiss1, battleMiss2, .empty],
        frameDuration: 0.25,
        loops: false
    )

    // Explosion: 3-frame sequence
    static let explosion = SpriteAnimation(
        frames: [explosion1, explosion2, explosion3],
        frameDuration: 0.15,
        loops: false
    )

    // Frame 1: small central burst
    static let explosion1 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0180, //  .......##.......
        0x03C0, //  ......####......
        0x07E0, //  .....######.....
        0x07E0, //  .....######.....
        0x03C0, //  ......####......
        0x0180, //  .......##.......
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Frame 2: medium starburst
    static let explosion2 = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0180, //  .......##.......
        0x0180, //  .......##.......
        0x0240, //  ......#..#......  rays
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...
        0x3FFC, //  ..############..
        0x3FFC, //  ..############..
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x0240, //  ......#..#......
        0x0180, //  .......##.......
        0x0180, //  .......##.......
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Frame 3: large blast with debris
    static let explosion3 = SpriteFrame(rows: [
        0x2004, //  ..#..........#..  debris
        0x0810, //  ....#......#....
        0x0180, //  .......##.......
        0x1008, //  ...#.........#..
        0x0660, //  .....##..##.....  ring
        0x1818, //  ...##......##...
        0x2004, //  ..#..........#..
        0x4002, //  .#............#.  outer ring
        0x4002, //  .#............#.
        0x2004, //  ..#..........#..
        0x1818, //  ...##......##...
        0x0660, //  .....##..##.....
        0x1008, //  ...#.........#..
        0x0180, //  .......##.......
        0x0810, //  ....#......#....
        0x2004  //  ..#..........#..
    ])
}
