import Foundation

extension SharedSprites {

    // MARK: - Healing

    // Syringe with plunger up — ready to inject
    //
    //    ......##........  plunger handle
    //    ......##........  plunger shaft
    //    ......##........
    //    ....######......  barrel top
    //    ....##..##......  barrel body
    //    ....##..##......
    //    ....##..##......
    //    ....######......  barrel bottom
    //    ......##........  needle
    //    ......##........

    private static let needleUp = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0300, //  ......##........  plunger handle
        0x0300, //  ......##........  plunger shaft
        0x0300, //  ......##........
        0x0FC0, //  ....######......  barrel top
        0x0CC0, //  ....##..##......  barrel body
        0x0CC0, //  ....##..##......
        0x0CC0, //  ....##..##......
        0x0FC0, //  ....######......  barrel bottom
        0x0300, //  ......##........  needle
        0x0300, //  ......##........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Syringe with plunger pressed — fluid injected
    //
    //    ....######......  barrel top
    //    ....######......  barrel body (filled)
    //    ....######......
    //    ....######......
    //    ....######......  barrel bottom
    //    ......##........  needle
    //    ......##........

    private static let needleDown = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0FC0, //  ....######......  barrel top
        0x0FC0, //  ....######......  filled
        0x0FC0, //  ....######......
        0x0FC0, //  ....######......
        0x0FC0, //  ....######......  barrel bottom
        0x0300, //  ......##........  needle
        0x0300, //  ......##........
        0x0000, //  ................
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    /// Needle injection — plunger up/down loop (0.3s per frame)
    static let needleInjection = SpriteAnimation(
        frames: [needleUp, needleDown],
        frameDuration: 0.3,
        loops: true
    )
}
