import Foundation

// MARK: - Mamemon (Ultimate) - round body, big glove hand

extension SpriteCatalog {

    static func mamemonFrames(
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        let idle1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x03C0, //  ......####......  head
            0x07E0, //  .....######.....
            0x0FF0, //  ....########....
            0x0DB0, //  ....##.##.##....  eyes
            0x0FF0, //  ....########....
            0x0FF0, //  ....########....  body
            0x1FF8, //  ...##########...
            0x1FF8, //  ...##########...
            0xFFF0, //  ############....  big glove arm
            0xFFF0, //  ############....
            0x1FF8, //  ...##########...
            0x0FF0, //  ....########....
            0x0480, //  .....#..#.......  legs
            0x0CC0  //  ....##..##......  feet
        ])

        let idle2 = SpriteFrame(rows: [
            0x0000, 0x0000,
            0x03C0, 0x07E0, 0x0FF0,
            0x0DB0, 0x0FF0, 0x0FF0,
            0x1FF8, 0x1FF8,
            0x0FFF, //  ....############  glove other side
            0x0FFF,
            0x1FF8,
            0x0FF0,
            0x0480,
            0x0CC0
        ])

        // Smiley Bomb (Mega Bomb) — glove winds up, punches with starburst
        let attack1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x03C0, //  ......####......  head
            0x07E0, //  .....######.....
            0x0FF0, //  ....########....
            0x0DB0, //  ....##.##.##....  eyes
            0x0FF0, //  ....########....
            0x0FF0, //  ....########....  body
            0x1FF8, //  ...##########...
            0x1FF8, //  ...##########...
            0x1FFC, //  ...###########..  glove wound back
            0x1FFC, //  ...###########..
            0x1FF8, //  ...##########...
            0x0FF0, //  ....########....
            0x0480, //  .....#..#.......
            0x0CC0  //  ....##..##......
        ])

        let attack2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x03C0, //  ......####......
            0x07E0, //  .....######.....
            0x0FF0, //  ....########....
            0x0DB0, //  ....##.##.##....
            0x0FF0, //  ....########....
            0x0FF0, //  ....########....
            0x1FF8, //  ...##########...
            0x1FFB, //  ...##########.##  glove extended
            0xFFFF, //  ################  glove + burst
            0xFFFF, //  ################  starburst
            0x1FFB, //  ...##########.##  burst dots
            0x0FF0, //  ....########....
            0x0480, //  .....#..#.......
            0x0CC0  //  ....##..##......
        ])

        // Side-walk: round body side, glove arm visible on one side
        let sideWalk1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x03C0, //  ......####......  head
            0x07E0, //  .....######.....
            0x0FF0, //  ....########....
            0x0DB0, //  ....##.##.##....  eyes
            0x0FF0, //  ....########....
            0x0FF0, //  ....########....  body
            0x1FF8, //  ...##########...
            0x3FF8, //  ..###########...  glove side
            0x3FF0, //  ..##########....
            0x1FF0, //  ...#########....
            0x1FF8, //  ...##########...
            0x0FF0, //  ....########....
            0x0480, //  .....#..#.......  legs stride
            0x0840  //  ....#....#......  feet apart
        ])

        let sideWalk2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x03C0, //  ......####......  head
            0x07E0, //  .....######.....
            0x0FF0, //  ....########....
            0x0DB0, //  ....##.##.##....  eyes
            0x0FF0, //  ....########....
            0x0FF0, //  ....########....  body
            0x1FF8, //  ...##########...
            0x3FF8, //  ..###########...  glove side
            0x3FF0, //  ..##########....
            0x1FF0, //  ...#########....
            0x1FF8, //  ...##########...
            0x0FF0, //  ....########....
            0x0480, //  .....#..#.......  legs together
            0x0CC0  //  ....##..##......  feet
        ])

        switch kind {
        case .idle, .walk:
            return [idle1, idle2]
        case .sideWalk:
            return [sideWalk1, sideWalk2]
        case .happy, .eat, .sleep:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        case .attack:
            return [
                idle1.shiftedRight(1),
                attack1,
                attack2,
                attack2.overlaying(SharedSprites.impactBurst)
            ]
        }
    }
}
