import Foundation

// MARK: - Meramon (Champion) - humanoid fire creature

extension SpriteCatalog {

    static func meramonFrames(
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        let idle1 = SpriteFrame(rows: [
            0x0100, //  .......#........  flame tip
            0x0380, //  ......###.......  flame
            0x07C0, //  .....#####......  flame/head
            0x0FE0, //  ....#######.....  head
            0x0DA0, //  ....##.##.#.....  eyes
            0x07C0, //  .....#####......
            0x03C0, //  ......####......  neck
            0x0FF0, //  ....########....  body
            0x1FF8, //  ...##########...
            0x3FFC, //  ..############..  arms out
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x07E0, //  .....######.....
            0x0240, //  ......#..#......  legs
            0x0660, //  .....##..##.....  feet
            0x0000  //  ................
        ])

        let idle2 = SpriteFrame(rows: [
            0x0280, //  ......#.#.......  flickering flame
            0x05C0, //  .....#.###......
            0x0FE0, //  ....#######.....
            0x0FE0, //  ....#######.....
            0x0DA0, //  ....##.##.#.....
            0x07C0, //  .....#####......
            0x03C0, //  ......####......
            0x0FF0, //  ....########....
            0x1FF8, //  ...##########...
            0x3FFC, //  ..############..
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x07E0, //  .....######.....
            0x0240, //  ......#..#......
            0x0660, //  .....##..##.....
            0x0000
        ])

        // Burning Fist (Magma Bomb) — flame larger, body leans, fist extends
        let attack1 = SpriteFrame(rows: [
            0x0380, //  ......###.......  flame flickers larger
            0x07C0, //  .....#####......
            0x0FE0, //  ....#######.....  head
            0x0FE0, //  ....#######.....
            0x0DA0, //  ....##.##.#.....  eyes
            0x07C0, //  .....#####......
            0x03C0, //  ......####......  neck
            0x0FF0, //  ....########....  body leaning
            0x1FF8, //  ...##########...
            0x1FF8, //  ...##########...  arms pulled back
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x07E0, //  .....######.....
            0x0240, //  ......#..#......
            0x0660, //  .....##..##.....
            0x0000  //  ................
        ])

        let attack2 = SpriteFrame(rows: [
            0x0380, //  ......###.......  flame
            0x07C0, //  .....#####......
            0x0FE0, //  ....#######.....
            0x0FE0, //  ....#######.....
            0x0DA0, //  ....##.##.#.....
            0x07C0, //  .....#####......
            0x03C0, //  ......####......
            0x0FF6, //  ....########.##.  fist extending
            0x1FFF, //  ...#############  fist + flame aura
            0x1FFE, //  ...############.  burning fist
            0x0FF6, //  ....########.##.  flame aura
            0x07E0, //  .....######.....
            0x07E0, //  .....######.....
            0x0240, //  ......#..#......
            0x0660, //  .....##..##.....
            0x0000  //  ................
        ])

        switch kind {
        case .idle, .walk:
            return [idle1, idle2]
        case .happy, .eat, .sleep:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        case .attack:
            return [
                idle1.shiftedRight(1),
                attack1,
                attack2,
                attack2.overlaying(SharedSprites.impactBurst)
            ]
        }
    }
}
