import Foundation

// MARK: - Tyrannomon (Champion) - red dinosaur, bulky

extension SpriteCatalog {

    static func tyrannomonFrames(
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        let idle1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x07C0, //  .....#####......  head
            0x0FE0, //  ....#######.....
            0x0DA0, //  ....##.##.#.....  eye
            0x0FE0, //  ....#######.....
            0x07C0, //  .....#####......  neck
            0x0FE0, //  ....#######.....  body
            0x1FF0, //  ...#########....
            0x5FF0, //  .#.#########....  arms
            0x1FF0, //  ...#########....
            0x0FE0, //  ....#######.....
            0x0FE0, //  ....#######.....  tail
            0x0920, //  ....#..#..#.....  legs
            0x1930, //  ...##..#..##....  feet
            0x0000  //  ................
        ])

        let idle2 = SpriteFrame(rows: [
            0x0000, 0x0000,
            0x07C0, 0x0FE0, 0x0DA0, 0x0FE0,
            0x07C0, 0x0FE0, 0x1FF0, 0x5FF0,
            0x1FF0, 0x0FE0, 0x0FE0,
            0x1220, //  ...#..#..#......  alt legs
            0x1230, //  ...#..#..##.....
            0x0000
        ])

        // Fire Breath (Blaze Blast) — head forward, mouth wide, flame cluster
        let attack1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x07C0, //  .....#####......  head
            0x0FE0, //  ....#######.....
            0x0DA0, //  ....##.##.#.....  eye
            0x0FE0, //  ....#######.....
            0x0E00, //  ....###.........  mouth wide open
            0x0FE0, //  ....#######.....  body
            0x1FF0, //  ...#########....
            0x5FF0, //  .#.#########....  arms
            0x1FF0, //  ...#########....
            0x0FE0, //  ....#######.....
            0x0FE0, //  ....#######.....
            0x0920, //  ....#..#..#.....
            0x1930, //  ...##..#..##....
            0x0000  //  ................
        ])

        let attack2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x07C0, //  .....#####......  head
            0x0FE0, //  ....#######.....
            0x0DA0, //  ....##.##.#.....  eye
            0x0FE0, //  ....#######.....
            0x0E1E, //  ....###....####.  flame blast
            0x0FEF, //  ....#######.####  flame cluster
            0x1FF6, //  ...#########.##.  flame wisps
            0x5FF0, //  .#.#########....
            0x1FF0, //  ...#########....
            0x0FE0, //  ....#######.....
            0x0FE0, //  ....#######.....
            0x0920, //  ....#..#..#.....
            0x1930, //  ...##..#..##....
            0x0000  //  ................
        ])

        switch kind {
        case .idle, .walk:
            return [idle1, idle2]
        case .happy, .eat, .sleep:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        case .attack:
            return [
                idle1.shiftedRight(1),
                attack1,
                attack2,
                attack2.overlaying(SharedSprites.impactBurst)
            ]
        }
    }
}
