import Foundation

// MARK: - Seadramon (Champion) - sea serpent, long neck

extension SpriteCatalog {

    static func seadramonFrames(
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        let idle1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0780, //  .....####.......  head
            0x0FC0, //  ....######......
            0x0DC0, //  ....##.###......  eye
            0x0FC0, //  ....######......  jaw
            0x07C0, //  .....#####......  neck
            0x03C0, //  ......####......
            0x03C0, //  ......####......
            0x07E0, //  .....######.....  body thickens
            0x0FF0, //  ....########....
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x03F0, //  ......######....  tail
            0x01F8, //  .......######...
            0x00F8, //  ........#####...
            0x0030  //  ..........##....  tail tip
        ])

        let idle2 = SpriteFrame(rows: [
            0x0000,
            0x0780, 0x0FC0, 0x0DC0, 0x0FC0,
            0x07C0,
            0x03E0, //  ......#####.....  neck sway
            0x03E0,
            0x07E0,
            0x0FF0, 0x0FF0,
            0x07E0,
            0x03F0,
            0x01F8,
            0x00F8,
            0x0030
        ])

        // Ice Arrow — head lunges, ice crystal diamond shape
        let attack1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0780, //  .....####.......  head
            0x0FC0, //  ....######......
            0x0DC0, //  ....##.###......  eye
            0x0FE0, //  ....#######.....  head lunges forward
            0x07C0, //  .....#####......  neck
            0x03C0, //  ......####......  body coils tighter
            0x07C0, //  .....#####......
            0x0FE0, //  ....#######.....
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x03F0, //  ......######....
            0x01F8, //  .......######...
            0x00F8, //  ........#####...
            0x0030, //  ..........##....
            0x0000  //  ................
        ])

        let attack2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0780, //  .....####.......
            0x0FC2, //  ....######....#.  ice crystal top
            0x0DC6, //  ....##.###...##.  diamond forming
            0x0FEE, //  ....#######.###.  ice crystal wide
            0x07C6, //  .....#####...##.  diamond shape
            0x03C2, //  ......####....#.  ice crystal bottom
            0x07C0, //  .....#####......
            0x0FE0, //  ....#######.....
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x03F0, //  ......######....
            0x01F8, //  .......######...
            0x00F8, //  ........#####...
            0x0030, //  ..........##....
            0x0000  //  ................
        ])

        // Side-walk: sea serpent side, long neck, undulating body
        let sideWalk1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0F00, //  ....####........  head crest
            0x1F80, //  ...######.......
            0x1B80, //  ...##.###.......  eye
            0x1F80, //  ...######.......
            0x0F00, //  ....####........  jaw
            0x0700, //  .....###........  neck
            0x0700, //  .....###........
            0x0F80, //  ....#####.......  body thickens
            0x1FC0, //  ...#######......
            0x1FC0, //  ...#######......
            0x0FE0, //  ....#######.....
            0x07F0, //  .....#######....  tail
            0x03F8, //  ......#######...
            0x01F0, //  .......#####....
            0x0060  //  .........##.....  tail tip
        ])

        let sideWalk2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0F00, //  ....####........  head crest
            0x1F80, //  ...######.......
            0x1B80, //  ...##.###.......  eye
            0x1F80, //  ...######.......
            0x0F00, //  ....####........  jaw
            0x0780, //  .....####.......  neck sway
            0x0780, //  .....####.......
            0x0FC0, //  ....######......  body
            0x1FC0, //  ...#######......
            0x1FE0, //  ...########.....
            0x0FF0, //  ....########....
            0x07F0, //  .....#######....  tail
            0x03F8, //  ......#######...
            0x01F0, //  .......#####....
            0x0060  //  .........##.....  tail tip
        ])

        switch kind {
        case .idle, .walk:
            return [idle1, idle2]
        case .sideWalk:
            return [sideWalk1, sideWalk2]
        case .happy, .eat, .sleep:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        case .attack:
            return [
                idle1.shiftedRight(1),
                attack1,
                attack2,
                attack2.overlaying(SharedSprites.impactBurst)
            ]
        }
    }
}
