import Foundation

// MARK: - Sludgekin (Champion) - slug/blob, simple shape

nonisolated extension SpriteCatalog {

    static func sludgekinFrames(
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        let idle1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0180, //  .......##.......  eye stalks
            0x0180, //  .......##.......
            0x07E0, //  .....######.....  head
            0x0FF0, //  ....########....
            0x1BD8, //  ...##.####.##...  eyes
            0x1FF8, //  ...##########...
            0x1C38, //  ...###....###...  mouth
            0x1FF8, //  ...##########...
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....  slime trail
            0x0000  //  ................
        ])

        let idle2 = SpriteFrame(rows: [
            0x0000, 0x0000, 0x0000, 0x0000,
            0x0180, //  eye stalks
            0x0180,
            0x0000,
            0x07E0,
            0x0FF0,
            0x1BD8,
            0x1FF8,
            0x1C38,
            0x1FF8,
            0x0FF0,
            0x0FF0, //  wider at bottom (squish)
            0x0000
        ])

        // Poop Toss (Gu Throw) — rears back, flings poop forward
        let attack1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................  eye stalks retracted
            0x00C0, //  ........##......  shifted right (rearing back)
            0x03F0, //  ......######....
            0x07F8, //  .....########...
            0x0DEC, //  ....##.####.##..  eyes
            0x0FFC, //  ....##########..
            0x0E1C, //  ....###....###..  mouth
            0x0FFC, //  ....##########..
            0x07F8, //  .....########...
            0x03F0, //  ......######....
            0x0000  //  ................
        ])

        let attack2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0C00, //  ....##..........  poop 1 flying
            0x1E00, //  ...####.........
            0x0C00, //  ....##..........
            0x0180, //  .......##.......  eye stalks back
            0x0180, //  .......##.......
            0x07E0, //  .....######.....
            0x0FF0, //  ....########....  poop 2 flying
            0x1BD8, //  ...##.####.##...  eyes
            0x1C38, //  ...###....###...  mouth open
            0x1FF8, //  ...##########...
            0x0FF0, //  ....########....
            0x07E0, //  .....######.....
            0x0000  //  ................
        ])

        // Side profile facing left: slime mound, single eye toward
        // the foe, wide body tapering up.
        let sideWalk1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0380, //  ......###.......
            0x07C0, //  .....#####......
            0x0EE0, //  ....###.###.....  eye
            0x0FE0, //  ....#######.....
            0x1FF0, //  ...#########....
            0x3FF0, //  ..##########....
            0x7FF8, //  .############...
            0x7BF8, //  .####.#######...
            0x7FF8, //  .############...
            0x7FF8, //  .############...
            0xFFF0, //  ############....
            0xFFFC, //  ##############..  wide base
            0x7FF8, //  .############...
            0x0000  //  ................
        ])

        // Bobbed down — second stance frame.
        let sideWalk2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0380, //  ......###.......
            0x07C0, //  .....#####......
            0x0EE0, //  ....###.###.....  eye
            0x0FE0, //  ....#######.....
            0x1FF0, //  ...#########....
            0x3FF0, //  ..##########....
            0x7FF8, //  .############...
            0x7FF8, //  .############...
            0x7FF8, //  .############...
            0xFFF0, //  ############....
            0xFFFC, //  ##############..  wide base
            0x7FF8, //  .############...
            0x0000  //  ................
        ])

        switch kind {
        case .idle, .walk:
            return [idle1, idle2]
        case .sideWalk:
            return [sideWalk1, sideWalk2]
        case .happy, .eat, .sleep:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        case .attack:
            return [
                idle1.shiftedRight(1),
                attack1,
                attack2,
                idle1
            ]
        case .refuse:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        }
    }
}
