import Foundation

// MARK: - Marshkin (Rookie) - amphibian/lizard, low to the ground

nonisolated extension SpriteCatalog {

    // Marshkin: wide frog-like body, fin on back, low stance

    static func marshkinFrames(
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        let idle1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0200, //  ......#.........  fin tip
            0x0700, //  .....###........  fin
            0x0F80, //  ....#####.......  head
            0x1FC0, //  ...#######......
            0x3740, //  ..##.###.#......  eyes
            0x3FE0, //  ..#########.....
            0x7FF0, //  .###########....  body
            0x7FF0, //  .###########....
            0x3FE0, //  ..#########.....
            0x1FC0, //  ...#######......
            0x1240, //  ...#..#..#.#....  feet
            0x0000  //  ................
        ])

        let idle2 = SpriteFrame(rows: [
            0x0000, 0x0000, 0x0000, 0x0000,
            0x0000,
            0x0200, //  fin tip
            0x0700, //  fin
            0x0F80, //  head
            0x1FC0,
            0x3740, //  eyes
            0x3FE0,
            0x7FF0, //  body
            0x7FF0,
            0x3FE0,
            0x1FC0,
            0x1240  //  feet
        ])

        // Electric Shock (Dengeki) — crouches, fin raised, lightning bolt
        let attack1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0200, //  ......#.........  fin raised higher
            0x0700, //  .....###........  fin
            0x0F80, //  ....#####.......  head
            0x1FC0, //  ...#######......
            0x3740, //  ..##.###.#......  eyes, mouth opening
            0x3FC0, //  ..########......
            0x7FF0, //  .###########....  body crouched
            0x7FF0, //  .###########....
            0x3FE0, //  ..#########.....
            0x1FC0, //  ...#######......
            0x1FC0, //  ...#######......  feet planted
            0x0000, //  ................
            0x0000  //  ................
        ])

        // Side-walk: flat lizard side, fin on top, long low body
        let sideWalk1 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0400, //  .....#..........
            0x0E00, //  ....###.........
            0x1F00, //  ...#####........
            0x3F80, //  ..#######.......
            0x3780, //  ..##.####.......
            0x7FC0, //  .#########......
            0x7FC0, //  .#########......
            0x3FE0, //  ..#########.....
            0x1FF0, //  ...#########....
            0x0FF8, //  ....#########...
            0x1240, //  ...#..#..#......
            0x0000 //  ................
        ])

        let sideWalk2 = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0400, //  .....#..........
            0x0E00, //  ....###.........
            0x1F00, //  ...#####........
            0x3F80, //  ..#######.......
            0x3780, //  ..##.####.......
            0x7FC0, //  .#########......
            0x7FC0, //  .#########......
            0x3FE0, //  ..#########.....
            0x1FF0, //  ...#########....
            0x0A40, //  ....#.#..#......
            0x0000 //  ................
        ])

        switch kind {
        case .idle, .walk:
            return [idle1, idle2]
        case .sideWalk:
            return [sideWalk1, sideWalk2]
        case .happy, .eat, .sleep:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        case .attack:
            return strike(idle: idle1, attack1)
        case .refuse:
            return defaultAnimationFromIdle(idle1, idle2, kind)
        }
    }
}
