import Foundation

/// Pixel art sprite data for all Creature species.
/// Each sprite is a 16x16 monochrome bitmap encoded as 16 UInt16 rows
/// (MSB = left). Per-species frame data lives in the `SpriteCatalog+<Species>`
/// extensions, whose hex rows and ASCII-art comments are generated by the
/// Tools/ pipeline; this file owns per-kind timing and the derived default
/// animations for species without dedicated art.
nonisolated enum SpriteCatalog {

    nonisolated enum AnimationKind: Sendable {
        case idle
        case walk
        case sideWalk
        case happy
        case eat
        case sleep
        case attack
        case refuse
    }

    static func animation(
        for species: PetSpecies,
        kind: AnimationKind
    ) -> SpriteAnimation {
        let frames = self.frames(for: species, kind: kind)

        let duration: TimeInterval
        let loops: Bool

        switch kind {
        case .idle:
            duration = 0.5
            loops = true
        case .walk:
            duration = 0.35
            loops = true
        case .sideWalk:
            duration = 0.35
            loops = true
        case .happy:
            duration = 0.25
            loops = true
        case .eat:
            duration = 0.3
            loops = false
        case .sleep:
            duration = 0.9
            loops = true
        case .attack:
            duration = 0.2
            loops = false
        case .refuse:
            duration = 0.15
            loops = false
        }

        return SpriteAnimation(
            frames: frames,
            frameDuration: duration,
            loops: loops
        )
    }
}

// MARK: - Frame Dispatch

nonisolated extension SpriteCatalog {

    static func frames(
        for species: PetSpecies,
        kind: AnimationKind
    ) -> [SpriteFrame] {
        return switch species {
        case .dotkin: dotkinFrames(kind)
        case .hopkin: hopkinFrames(kind)
        case .emberkin: emberkinFrames(kind)
        case .marshkin: marshkinFrames(kind)
        case .rexkin: rexkinFrames(kind)
        case .blazekin: blazekinFrames(kind)
        case .dreadkin: dreadkinFrames(kind)
        case .pyrekin: pyrekinFrames(kind)
        case .galekin: galekinFrames(kind)
        case .tidekin: tidekinFrames(kind)
        case .sludgekin: sludgekinFrames(kind)
        case .steelkin: steelkinFrames(kind)
        case .orbkin: orbkinFrames(kind)
        case .plushkin: plushkinFrames(kind)
        }
    }
}

// Species projectiles live in SpriteCatalog+Projectiles.swift.

// MARK: - Default Animation Helpers

nonisolated extension SpriteCatalog {

    /// Generates derived animations from the two idle frames for species
    /// without dedicated animation data, using sprite transformations.
    static func defaultAnimationFromIdle(
        _ idle1: SpriteFrame,
        _ idle2: SpriteFrame,
        _ kind: AnimationKind
    ) -> [SpriteFrame] {
        switch kind {
        case .idle, .walk:
            return [idle1, idle2]

        case .sideWalk:
            return defaultSideWalkFromIdle(idle1, idle2)

        case .happy:
            // Bounce: crouch → jump → peak → land with dust
            return [
                idle1.shiftedDown(1),
                idle1.shiftedUp(2),
                idle1.shiftedUp(1),
                idle1.overlaying(SharedSprites.landingDust)
            ]

        case .eat:
            // Chomp: lean → bite → chew → lean back
            return [
                idle1.shiftedLeft(1),
                idle2.shiftedLeft(1),
                idle1.shiftedLeft(1),
                idle1
            ]

        case .sleep:
            // Breathing with Z's cycling at different heights
            return [
                idle1.overlaying(SharedSprites.sleepZ1),
                idle1.overlaying(SharedSprites.sleepZ2),
                idle2.overlaying(SharedSprites.sleepZ3),
                idle2.overlaying(SharedSprites.sleepZ2)
            ]

        case .attack:
            // Strike: windup → two lunge beats → return to windup
            return [
                idle1.shiftedRight(1),
                idle1.shiftedLeft(2),
                idle1.shiftedLeft(2),
                idle1.shiftedRight(1)
            ]

        case .refuse:
            // Head shake: left → right → left → idle
            return [
                idle1.shiftedLeft(1),
                idle1.shiftedRight(1),
                idle1.shiftedLeft(1),
                idle1
            ]
        }
    }

    /// A weak, sagging loop derived from the idle frames — no per-species art,
    /// matching how sleep/happy are derived. Slow and drooping so a languishing
    /// pet reads as faint; paired on-screen with the flashing Call sign.
    static func weakAnimation(for species: PetSpecies) -> SpriteAnimation {
        let idle = frames(for: species, kind: .idle)
        let idle1 = idle.first ?? .empty
        let idle2 = idle.count > 1 ? idle[1] : idle1
        return SpriteAnimation(
            frames: [
                idle1.shiftedDown(1),
                idle1.shiftedDown(2),
                idle2.shiftedDown(1),
                idle1.shiftedDown(2)
            ],
            frameDuration: 0.7,
            loops: true
        )
    }

    /// Happy bounce: crouch, two celebration beats, land in dust.
    static func bounceHappy(
        idle: SpriteFrame,
        _ happy1: SpriteFrame,
        _ happy2: SpriteFrame
    ) -> [SpriteFrame] {
        [
            idle.shiftedDown(1),
            happy1,
            happy2,
            idle.overlaying(SharedSprites.landingDust)
        ]
    }

    /// Chomp: open, clamp, open, settle back to the rest frame.
    static func chomp(
        _ eat1: SpriteFrame,
        _ eat2: SpriteFrame,
        rest: SpriteFrame
    ) -> [SpriteFrame] {
        [eat1, eat2, eat1, rest]
    }

    /// Strike: a simple mouth-open tell — windup shift, two beats of the
    /// species' first attack pose, then back to the windup. The
    /// projectile-forming pose is dropped; the actual projectile is
    /// shown in its own phase.
    static func strike(
        idle: SpriteFrame,
        _ attack1: SpriteFrame
    ) -> [SpriteFrame] {
        [
            idle.shiftedRight(1),
            attack1,
            attack1,
            idle.shiftedRight(1)
        ]
    }

    /// Sleep loop: two custom beats, optionally interleaved with Z's pulsing
    /// over a base frame (pass nil to just alternate the two beats).
    static func sleepCycle(
        _ sleep1: SpriteFrame,
        _ sleep2: SpriteFrame,
        overlayingZOn base: SpriteFrame? = nil
    ) -> [SpriteFrame] {
        guard let base else { return [sleep1, sleep2, sleep1, sleep2] }
        return [
            sleep1,
            base.overlaying(SharedSprites.sleepZ2),
            sleep2,
            base.overlaying(SharedSprites.sleepZ3)
        ]
    }

    /// Defeated slump: the pet sags low and heaves on the spot, head hung.
    /// Built from the first idle frame only — unlike `weakAnimation` it never
    /// cycles to the second idle, so species whose idle glances around don't
    /// look about mid-defeat.
    static func defeatAnimation(for species: PetSpecies) -> SpriteAnimation {
        let idle1 = frames(for: species, kind: .idle).first ?? .empty
        return SpriteAnimation(
            frames: [idle1.shiftedDown(1), idle1.shiftedDown(2)],
            frameDuration: 0.8,
            loops: true
        )
    }

    /// Generates a simple 2-frame side-walk from idle frames
    /// using horizontal shift as a placeholder side profile.
    static func defaultSideWalkFromIdle(
        _ idle1: SpriteFrame,
        _ idle2: SpriteFrame
    ) -> [SpriteFrame] {
        [idle1.shiftedLeft(1), idle2.shiftedLeft(1)]
    }
}
