import Foundation

// MARK: - Side-Profile Animations (Battle & Training)

nonisolated extension SpriteCatalog {

    /// Side-profile standing stance, facing the opponent/target.
    static func sideStance(
        for species: PetSpecies
    ) -> SpriteAnimation {
        SpriteAnimation(
            frames: frames(for: species, kind: .sideWalk),
            frameDuration: 0.5,
            loops: true
        )
    }

    /// Species-specific side-profile attack pose. Species without a
    /// dedicated attack hold their side stance.
    static func sideAttack(
        for species: PetSpecies
    ) -> SpriteAnimation {
        switch species {
        case .hopkin:
            let ready = frames(for: .hopkin, kind: .sideWalk).first
                ?? .empty
            return SpriteAnimation(
                frames: [
                    ready, hopkinMouthHalf,
                    hopkinMouthWide, hopkinMouthWide
                ],
                frameDuration: 0.18,
                loops: false
            )
        case .emberkin: return mouthChomp(.emberkin, emberkinMouthWide)
        case .rexkin: return mouthChomp(.rexkin, rexkinMouthWide)
        case .blazekin: return mouthChomp(.blazekin, blazekinMouthWide)
        case .galekin: return mouthChomp(.galekin, galekinMouthWide)
        case .tidekin: return mouthChomp(.tidekin, tidekinMouthWide)
        case .sludgekin: return mouthChomp(.sludgekin, sludgekinMouthWide)
        case .steelkin: return mouthChomp(.steelkin, steelkinMouthWide)
        case .dreadkin: return mouthChomp(.dreadkin, dreadkinMouthWide)
        case .pyrekin: return mouthChomp(.pyrekin, pyrekinMouthWide)
        case .dotkin: return mouthChomp(.dotkin, dotkinMouthWide)
        case .marshkin: return mouthChomp(.marshkin, marshkinMouthWide)
        case .orbkin: return mouthChomp(.orbkin, orbkinMouthWide)
        case .plushkin: return mouthChomp(.plushkin, plushkinMouthWide)
        }
    }

    /// Opens from the side stance to a held mouth-wide pose.
    private static func mouthChomp(
        _ species: PetSpecies,
        _ wide: SpriteFrame
    ) -> SpriteAnimation {
        let ready = frames(for: species, kind: .sideWalk).first
            ?? .empty
        return SpriteAnimation(
            frames: [ready, wide, wide],
            frameDuration: 0.2,
            loops: false
        )
    }

    // Hopkin's mouth-open chomp (native facing left). The back of the
    // body stays full — only the front (mouth) opens.
    private static let hopkinMouthHalf = SpriteFrame(rows: [
        0x0000, //  ................
        0x01C0, //  .......###......
        0x0380, //  ......###.......
        0x0780, //  .....####.......
        0x1FC0, //  ...#######......
        0x3FE0, //  ..#########.....
        0x7FF0, //  .###########....
        0x6FF0, //  .##.########....  eye
        0x6FF0, //  .##.########....
        0x3FF0, //  ..##########....  mouth opening
        0x7FE0, //  .##########.....
        0x3FC0, //  ..########......
        0x1F80, //  ...######.......
        0x0F00, //  ....####........
        0x0000, //  ................
        0x0000  //  ................
    ])

    private static let hopkinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x01C0, //  .......###......
        0x0380, //  ......###.......
        0x0780, //  .....####.......
        0x1FC0, //  ...#######......
        0x3FE0, //  ..#########.....
        0x7FF0, //  .###########....  back stays full
        0x6FF0, //  .##.########....  eye
        0x6FF0, //  .##.########....
        0x1FF0, //  ...#########....  upper lip
        0x0FF0, //  ....########....  mouth wide open
        0x3FE0, //  ..#########.....  lower jaw
        0x3FC0, //  ..########......
        0x1F80, //  ...######.......
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Dino mouth-open (native left): head front splits, body intact.
    private static let emberkinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0F00, //  ....####........
        0x1F80, //  ...######.......
        0x1B80, //  ...##.###.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x3C00, //  ..####..........  lower jaw forward
        0x1F80, //  ...######.......  body
        0x1F80, //  ...######.......
        0x0FC0, //  ....######......
        0x0F00, //  ....####........
        0x0F00, //  ....####........
        0x0900, //  ....#..#........
        0x1100, //  ...#...#........
        0x0000  //  ................
    ])

    private static let rexkinMouthWide = SpriteFrame(rows: [
        0x0600, //  .....##.........  horn
        0x0F00, //  ....####........
        0x1F80, //  ...######.......
        0x1B80, //  ...##.###.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x3E00, //  ..#####.........  lower jaw forward
        0x1F80, //  ...######.......  body
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x1FE0, //  ...########.....  tail
        0x0FF0, //  ....########....
        0x0FE0, //  ....#######.....
        0x0F00, //  ....####........
        0x0900, //  ....#..#........
        0x1100  //  ...#...#........
    ])

    private static let blazekinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0F00, //  ....####........
        0x1F80, //  ...######.......
        0x1B80, //  ...##.###.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x1F80, //  ...######.......  body
        0x3FC0, //  ..########......
        0x3FC0, //  ..########......
        0x1FE0, //  ...########.....  tail
        0x0FF0, //  ....########....
        0x0FE0, //  ....#######.....
        0x0F00, //  ....####........
        0x0900, //  ....#..#........
        0x1100  //  ...#...#........
    ])

    private static let galekinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0F00, //  ....####........
        0x1F80, //  ...######.......
        0x1D80, //  ...###.##.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x0FC0, //  ....######......  neck
        0x1FC0, //  ...#######......  wing
        0x3FE0, //  ..#########.....
        0x0FC0, //  ....######......  body
        0x07E0, //  .....######.....
        0x03F0, //  ......######....  tail
        0x01F8, //  .......######...
        0x00FC, //  ........######..
        0x007C, //  .........#####..
        0x0018  //  ...........##...
    ])

    private static let tidekinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0F00, //  ....####........
        0x1F80, //  ...######.......
        0x1B80, //  ...##.###.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x0FC0, //  ....######......  lower jaw
        0x0700, //  .....###........  neck
        0x0F80, //  ....#####.......  body
        0x1FC0, //  ...#######......
        0x1FC0, //  ...#######......
        0x0FE0, //  ....#######.....
        0x07F0, //  .....#######....  tail
        0x03F8, //  ......#######...
        0x01F0, //  .......#####....
        0x0060  //  .........##.....
    ])

    private static let sludgekinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0380, //  ......###.......
        0x07C0, //  .....#####......
        0x0EE0, //  ....###.###.....  eye
        0x0FE0, //  ....#######.....
        0x1FF0, //  ...#########....
        0x3FE0, //  ..#########.....  upper lip
        0x07F0, //  .....#######....  mouth open
        0x3FE0, //  ..#########.....  lower lip
        0x7FF8, //  .############...
        0x7FF8, //  .############...
        0xFFF0, //  ############....  base intact
        0xFFFC, //  ##############..
        0x7FF8, //  .############...
        0x0000  //  ................
    ])

    private static let steelkinMouthWide = SpriteFrame(rows: [
        0x0300, //  ......##........  horn
        0x0700, //  .....###........
        0x0F80, //  ....#####.......
        0x1FC0, //  ...#######......
        0x1BC0, //  ...##.####......  visor eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x1FC0, //  ...#######......  body
        0x3FE0, //  ..#########.....
        0x7FE0, //  .##########.....  wing
        0x3FE0, //  ..#########.....
        0x1FC0, //  ...#######......
        0x1FC0, //  ...#######......
        0x0F80, //  ....#####.......
        0x0D80, //  ....##.##.......
        0x1180  //  ...#...##.......
    ])

    private static let dreadkinMouthWide = SpriteFrame(rows: [
        0x0700, //  .....###........  horns
        0x0F80, //  ....#####.......
        0x1F80, //  ...######.......
        0x1B80, //  ...##.###.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x0F80, //  ....#####.......  body
        0x1FC0, //  ...#######......
        0x3FC0, //  ..########......  wing
        0x7F80, //  .########.......
        0x1FC0, //  ...#######......
        0x0F80, //  ....#####.......
        0x0700, //  .....###........  waist
        0x0700, //  .....###........
        0x0500, //  .....#.#........
        0x0900  //  ....#..#........
    ])

    private static let pyrekinMouthWide = SpriteFrame(rows: [
        0x0200, //  ......#.........  flame
        0x0700, //  .....###........
        0x0F80, //  ....#####.......
        0x1F80, //  ...######.......
        0x1B80, //  ...##.###.......  eye
        0x3E00, //  ..#####.........  upper jaw forward
        0x0700, //  .....###........  mouth gap
        0x0F80, //  ....#####.......  body
        0x1FC0, //  ...#######......
        0x1FC0, //  ...#######......
        0x0F80, //  ....#####.......
        0x0F00, //  ....####........
        0x0F00, //  ....####........
        0x0500, //  .....#.#........
        0x0900, //  ....#..#........
        0x0000  //  ................
    ])

    // Dotkin opens a mouth at the front (blob attack).
    private static let dotkinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x0300, //  ......##........  horn
        0x0500, //  .....#.#........
        0x03C0, //  ......####......
        0x0FF0, //  ....########....
        0x3FF0, //  ..##########....
        0x37E0, //  ..##.######.....  one eye + mouth
        0x1FE0, //  ...########.....
        0x3FF0, //  ..##########....
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x03C0, //  ......####......
        0x0000, //  ................
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Plushkin opens its muzzle (teddy attack).
    private static let plushkinMouthWide = SpriteFrame(rows: [
        0x1800, //  ...##...........  ear
        0x3C00, //  ..####..........
        0x3F00, //  ..######........
        0xFF00, //  ########........  muzzle open
        0xDF00, //  ##.#####........  eye + open
        0xFF00, //  ########........
        0x3F00, //  ..######........
        0x7FC2, //  .#########....#.  body + tail
        0x7FEC, //  .##########.##..
        0x7FF0, //  .###########....
        0x7FE0, //  .##########.....
        0x3FC0, //  ..########......
        0x6F60, //  .##.####.##.....
        0x6060, //  .##......##.....
        0x0000, //  ................
        0x0000  //  ................
    ])

    // Orbkin (bird) opens its beak to blow a gust — wind attack.
    private static let orbkinMouthWide = SpriteFrame(rows: [
        0x0000, //  ................
        0x0000, //  ................
        0x03C0, //  ......####......
        0x07E0, //  .....######.....
        0x1FF0, //  ...#########....
        0x35F8, //  ..##.#.######...  upper beak open
        0x05F8, //  .....#.######...  beak gap (blow)
        0x3DF8, //  ..####.######...  lower beak
        0x0FF0, //  ....########....
        0x1FF8, //  ...##########...  body
        0x1FFC, //  ...###########..  tail
        0x1FFE, //  ...############.
        0x1FF8, //  ...##########...
        0x0FF0, //  ....########....
        0x0480, //  .....#..#.......
        0x0CC0  //  ....##..##......
    ])

    private static let marshkinMouthWide = SpriteFrame(rows: [
            0x0000, //  ................
            0x0000, //  ................
            0x0000, //  ................
            0x0400, //  .....#..........
            0x0E00, //  ....###.........
            0x1F00, //  ...#####........
            0x3F80, //  ..#######.......
            0x1980, //  ...##..##.......
            0x7FC0, //  .#########......
            0x7FC0, //  .#########......
            0x3FE0, //  ..#########.....
            0x1FF0, //  ...#########....
            0x0FF8, //  ....#########...
            0x1240, //  ...#..#..#......
            0x0000, //  ................
            0x0000 //  ................
        ])
}
